# Generated by Django 6.0.6 on 2026-09-10 05:45

import apps.events.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_account_security_reviewed_at'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=apps.events.models._event_public_id, editable=False, max_length=40, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('customer_ref', models.CharField(blank=True, default='', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(default='api', max_length=40)),
                ('occurred_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_events', to='accounts.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_events', to='contacts.contact')),
            ],
            options={
                'ordering': ['-received_at', '-id'],
                'indexes': [models.Index(fields=['account', 'name', 'received_at'], name='business_ev_account_36d6fe_idx'), models.Index(fields=['account', 'received_at'], name='business_ev_account_d3ac83_idx')],
            },
        ),
    ]
