# Generated by Django 6.0.6 on 2026-09-18 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_account_security_reviewed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerticalActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vertical_activations', to='accounts.account')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'key'), name='unique_vertical_activation_per_account')],
            },
        ),
    ]
