# Generated by Django 6.0.6 on 2026-09-10 13:14

import apps.scheduler.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_account_security_reviewed_at'),
        ('email_service', '0034_alter_bulkemailcampaign_status_and_more'),
        ('whatsapp', '0009_whatsappbusinessnumber_verification_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=apps.scheduler.models._job_public_id, editable=False, max_length=40, unique=True)),
                ('kind', models.CharField(choices=[('email_single', 'Email (single)'), ('email_campaign', 'Email campaign'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('running', 'Running'), ('sent', 'Sent'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], db_index=True, default='scheduled', max_length=16)),
                ('fire_at', models.DateTimeField(db_index=True)),
                ('tz', models.CharField(default='UTC', max_length=64)),
                ('template_payload', models.JSONField(blank=True, default=dict)),
                ('idempotency_key', models.CharField(max_length=64, unique=True)),
                ('recurrence', models.CharField(blank=True, default='', max_length=255)),
                ('recurrence_until', models.DateTimeField(blank=True, null=True)),
                ('max_occurrences', models.PositiveIntegerField(blank=True, null=True)),
                ('occurrence_count', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('stale_grace_secs', models.PositiveIntegerField(default=21600)),
                ('fired_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_jobs', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='scheduler.scheduledjob')),
                ('target_campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_jobs', to='email_service.bulkemailcampaign')),
                ('target_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='email_service.emailmessage')),
                ('target_outbound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='whatsapp.outboundmessage')),
            ],
            options={
                'ordering': ['fire_at', 'id'],
                'indexes': [models.Index(fields=['status', 'fire_at'], name='scheduler_s_status_a930fd_idx'), models.Index(fields=['account', 'status', 'fire_at'], name='scheduler_s_account_0e6d11_idx')],
            },
        ),
    ]
