# Generated by Django 6.0.6 on 2026-09-26 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_businessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='scheduled_deletion_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
