# Generated by Django 6.1.1 on 2026-10-01 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessContext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_model",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("b2c", "B2C (direct to consumer)"),
                            ("b2b", "B2B (business to business)"),
                            ("both", "Both"),
                        ],
                        default="",
                        max_length=4,
                    ),
                ),
                ("customer_channels", models.JSONField(blank=True, default=list)),
                ("objectives", models.JSONField(blank=True, default=list)),
                ("capability_profile", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_context",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessKnowledge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("who_is_it_for", models.TextField(blank=True, default="")),
                ("problem_solved", models.TextField(blank=True, default="")),
                ("common_questions", models.JSONField(blank=True, default=list)),
                ("common_objections", models.JSONField(blank=True, default=list)),
                ("eligibility_rules", models.JSONField(blank=True, default=dict)),
                ("recommended_for", models.JSONField(blank=True, default=list)),
                ("faqs", models.JSONField(blank=True, default=list)),
                ("delivery_zones", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_knowledge",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
