# Generated by Django 6.0.6 on 2026-06-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="max_mailboxes",
            field=models.IntegerField(default=1),
        ),
    ]
