# Generated by Django 6.0.6 on 2026-06-17 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0005_plan_mailbox_storage_gb_plan_max_aliases_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_key", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
