# Generated by Django 6.0.6 on 2026-07-11 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0006_processedwebhookevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="api_rate_per_min",
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name="plan",
            name="outbound_webhooks",
            field=models.BooleanField(default=False),
        ),
    ]
