# Generated by Django 6.0.6 on 2026-08-19 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0010_seed_payment_methods"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="mailbox_storage_gb",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="max_aliases",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="max_forwarding_rules",
        ),
        migrations.RemoveField(
            model_name="plan",
            name="max_mailboxes",
        ),
    ]
