# Generated by Django 6.0.6 on 2026-08-23 14:10

from django.db import migrations


def seed_module_subscriptions(apps, schema_editor):
    """Populate ModuleSubscription rows from existing Plan booleans.

    For each account with a subscription, create ModuleSubscription rows
    based on their Plan's feature flags. This establishes the new model
    as the source of truth while maintaining backward compatibility.

    Modules seeded:
      - whatsapp: enabled if subscription exists
      - email: enabled if plan has email_apis=True
      - automation: enabled if subscription exists
      - payments: enabled if subscription exists and plan supports it
      - ai: disabled by default (Phase 5)

    Phase 4 approach: coexist with Plan booleans. During a 2-week period,
    both has_feature() checks will log fallback-hits. Once zeros, we drop
    the Plan fields in a cleanup PR.
    """
    apps.get_model("accounts", "Account")
    Subscription = apps.get_model("billing", "Subscription")
    apps.get_model("billing", "Plan")
    ModuleSubscription = apps.get_model("billing", "ModuleSubscription")

    for subscription in Subscription.objects.select_related("plan", "account"):
        account = subscription.account
        plan = subscription.plan

        # Email: enabled if plan has email_apis
        ModuleSubscription.objects.update_or_create(
            account=account,
            module="email",
            defaults={
                "subscription": subscription,
                "enabled": bool(plan.email_apis),
                "limits": {
                    "emails_per_month": plan.max_emails_per_month,
                    "bulk_recipients_per_campaign": plan.max_bulk_recipients_per_campaign,
                },
            },
        )

        # Automation: enabled for all active subscriptions
        ModuleSubscription.objects.update_or_create(
            account=account,
            module="automation",
            defaults={
                "subscription": subscription,
                "enabled": True,
                "limits": {
                    "max_rules": plan.max_automation_rules,
                },
            },
        )

        # WhatsApp: enabled for all active subscriptions
        ModuleSubscription.objects.update_or_create(
            account=account,
            module="whatsapp",
            defaults={
                "subscription": subscription,
                "enabled": True,
                "limits": {
                    "max_numbers": plan.max_whatsapp_numbers,
                    "max_conversations_per_month": plan.max_conversations_per_month,
                },
            },
        )

        # Payments: disabled by default (Phase 5)
        ModuleSubscription.objects.update_or_create(
            account=account,
            module="payments",
            defaults={
                "subscription": subscription,
                "enabled": False,
                "limits": {},
            },
        )

        # AI: disabled by default (Phase 5)
        ModuleSubscription.objects.update_or_create(
            account=account,
            module="ai",
            defaults={
                "subscription": subscription,
                "enabled": False,
                "limits": {},
            },
        )


def reverse_seed(apps, schema_editor):
    """Clear all ModuleSubscription rows during rollback."""
    ModuleSubscription = apps.get_model("billing", "ModuleSubscription")
    ModuleSubscription.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0012_create_module_subscription"),
    ]

    operations = [
        migrations.RunPython(seed_module_subscriptions, reverse_seed),
    ]
