# Generated by Django 6.0.6 on 2026-09-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0013_seed_module_subscriptions"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("email", "Email"),
                    ("whatsapp", "WhatsApp"),
                    ("both", "Email & WhatsApp"),
                ],
                default="email",
                max_length=10,
            ),
        ),
    ]
