# Generated by Django 6.0.6 on 2026-09-26 17:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_operator_console'),
        ('billing', '0020_seed_plan_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLimitOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_overrides', to='accounts.account')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('account', 'key')},
            },
        ),
        migrations.CreateModel(
            name='PlanLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.IntegerField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='billing.plan')),
            ],
            options={
                'unique_together': {('plan', 'key')},
            },
        ),
        migrations.CreateModel(
            name='UsageCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('period_start', models.DateField()),
                ('used', models.PositiveIntegerField(default=0)),
                ('warned_80', models.BooleanField(default=False)),
                ('warned_100', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_counters', to='accounts.account')),
            ],
            options={
                'unique_together': {('account', 'key', 'period_start')},
            },
        ),
        migrations.CreateModel(
            name='UsageReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50)),
                ('units', models.PositiveIntegerField(default=1)),
                ('operation_id', models.CharField(max_length=120)),
                ('period_start', models.DateField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved'), ('committed', 'Committed'), ('released', 'Released')], default='reserved', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_reservations', to='accounts.account')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='billing_usa_status_d3e416_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'key', 'operation_id'), name='unique_usage_operation')],
            },
        ),
    ]
