# Generated by Django 6.0.6 on 2026-09-26 18:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_seed_plan_limits'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_monthly_cost_per_business', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('target_margin_pct', models.PositiveSmallIntegerField(default=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(max_length=30, unique=True)),
                ('cost_per_unit', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
