# Generated by Django 6.0.6 on 2026-06-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_service", "0002_mailbox_emailalias"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildomain",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
