# Generated by Django 6.0.6 on 2026-08-19 14:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("email_service", "0015_systememailtemplate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailbox",
            name="account",
        ),
        migrations.RemoveField(
            model_name="mailbox",
            name="domain",
        ),
        migrations.DeleteModel(
            name="EmailAlias",
        ),
        migrations.DeleteModel(
            name="Mailbox",
        ),
    ]
