# Generated by Django 6.0.6 on 2026-09-09 09:57

import apps.email.models
from django.db import migrations, models


def backfill_public_ids(apps, schema_editor):
    EmailMessage = apps.get_model("email_service", "EmailMessage")
    from apps.email.models import _message_public_id

    qs = EmailMessage.objects.filter(public_id="").only("id")
    batch = []
    for msg in qs.iterator():
        msg.public_id = _message_public_id()
        batch.append(msg)
        if len(batch) >= 500:
            EmailMessage.objects.bulk_update(batch, ["public_id"])
            batch = []
    if batch:
        EmailMessage.objects.bulk_update(batch, ["public_id"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0023_alter_emailmessage_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='public_id',
            field=models.CharField(default='', editable=False, max_length=40),
        ),
        migrations.RunPython(backfill_public_ids, noop),
        migrations.AlterField(
            model_name='emailmessage',
            name='public_id',
            field=models.CharField(default=apps.email.models._message_public_id, editable=False, max_length=40, unique=True),
        ),
    ]
