# Generated by Django 6.0.6 on 2026-09-10 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_security_reviewed_at'),
        ('email_service', '0025_emailapikey_mode_emailmessage_key_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliverabilitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('score', models.PositiveIntegerField()),
                ('grade', models.CharField(default='', max_length=16)),
                ('checks', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverability_snapshots', to='accounts.account')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_service.emaildomain')),
            ],
            options={
                'ordering': ['-day'],
                'indexes': [models.Index(fields=['account', 'day'], name='email_servi_account_980a3a_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'domain', 'day'), name='uniq_deliverability_snapshot')],
            },
        ),
    ]
