# Generated by Django 6.0.6 on 2026-09-10 06:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0027_templatecomponent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailtemplateversion',
            options={'ordering': ['-number', '-created_at']},
        ),
        migrations.AddField(
            model_name='emailtemplateversion',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emailtemplateversion',
            name='label',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='emailtemplateversion',
            name='number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='emailtemplateversion',
            constraint=models.UniqueConstraint(fields=('template', 'number'), name='uniq_template_version_number'),
        ),
    ]
