# Generated by Django 6.0.6 on 2026-09-10 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0028_alter_emailtemplateversion_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='webhookendpoint',
            name='consecutive_failures',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='disabled_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webhookendpoint',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
