# Generated by Django 6.0.6 on 2026-09-10 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0029_webhookendpoint_consecutive_failures_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkEmailCampaignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=120)),
                ('from_email', models.EmailField(max_length=254)),
                ('subject_override', models.CharField(blank=True, default='', max_length=998)),
                ('text_override', models.TextField(blank=True, default='')),
                ('html_override', models.TextField(blank=True, default='')),
                ('template_version_number', models.PositiveIntegerField(blank=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('status_at_snapshot', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='email_service.bulkemailcampaign')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_service.emailtemplate')),
            ],
            options={
                'ordering': ['-number'],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'number'), name='uniq_campaign_version_number')],
            },
        ),
    ]
