# Generated by Django 6.0.6 on 2026-09-10 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0030_bulkemailcampaignversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplateLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=15)),
                ('subject', models.CharField(blank=True, default='', max_length=998)),
                ('text_body', models.TextField(blank=True, default='')),
                ('html_body', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locales', to='email_service.emailtemplate')),
            ],
            options={
                'ordering': ['locale'],
                'constraints': [models.UniqueConstraint(fields=('template', 'locale'), name='uniq_template_locale')],
            },
        ),
    ]
