# Generated by Django 6.0.6 on 2026-09-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0031_emailtemplatelocale'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmessage',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
