# Generated by Django 6.0.6 on 2026-09-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_service', '0034_alter_bulkemailcampaign_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('bounce', 'Hard Bounce'), ('complaint', 'Complaint (Abuse Report)'), ('invalid', 'Failed Validation'), ('manual', 'Manually Suppressed')], default='bounce', max_length=20)),
                ('bounce_type', models.CharField(blank=True, default='', help_text='SES bounce type: Permanent, Transient, or Undetermined', max_length=20)),
                ('source', models.CharField(default='ses_webhook', help_text='Where this suppression came from, e.g. ses_webhook, orphan_sns, manual', max_length=40)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['reason'], name='email_servi_reason_96d6fd_idx')],
            },
        ),
    ]
