# Generated by Django 6.0.6 on 2026-09-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("email_service", "0036_recipient_held"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildnsrecord",
            name="priority",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emaildomain",
            name="dns_diagnostics",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="emaildomain",
            name="dns_host",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="emaildomain",
            name="dns_zone",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="emaildomain",
            name="dns_zone_checked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emaildomain",
            name="mail_from_attempted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="emaildomain",
            name="mail_from_domain",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="emaildomain",
            name="mail_from_ok",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="emaildomain",
            name="mail_from_status",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="emaildnsrecord",
            name="key",
            field=models.CharField(
                choices=[
                    ("verify", "Domain verification"),
                    ("dkim", "DKIM"),
                    ("mfmx", "Bounce domain (MX)"),
                    ("mfspf", "Bounce domain SPF"),
                    ("spf", "SPF"),
                    ("dmarc", "DMARC"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="emaildnsrecord",
            name="record_type",
            field=models.CharField(
                choices=[("TXT", "TXT"), ("CNAME", "CNAME"), ("MX", "MX")],
                default="TXT",
                max_length=10,
            ),
        ),
    ]
