# Generated by Django 6.0.6 on 2026-09-10 05:31

import apps.contacts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_account_security_reviewed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=apps.contacts.models._contact_public_id, editable=False, max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('locale', models.CharField(blank=True, default='', max_length=15)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('subscribed', 'Subscribed'), ('unsubscribed', 'Unsubscribed'), ('bounced', 'Bounced'), ('complained', 'Complained')], default='subscribed', max_length=16)),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_engaged_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_contacts', to='accounts.account')),
            ],
            options={
                'ordering': ['-first_seen'],
            },
        ),
        migrations.CreateModel(
            name='ContactEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
                ('occurred_at', models.DateTimeField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_events', to='accounts.account')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='contacts.contact')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(blank=True, default='', max_length=255)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('mapping', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_imports', to='accounts.account')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_lists', to='accounts.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactListMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact')),
                ('contact_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contactlist')),
            ],
        ),
        migrations.AddField(
            model_name='contactlist',
            name='contacts',
            field=models.ManyToManyField(related_name='lists', through='contacts.ContactListMembership', to='contacts.contact'),
        ),
        migrations.CreateModel(
            name='CustomAttributeDef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('type', models.CharField(choices=[('string', 'Text'), ('number', 'Number'), ('boolean', 'Yes / no'), ('date', 'Date')], default='string', max_length=10)),
                ('label', models.CharField(blank=True, default='', max_length=150)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_attributes', to='accounts.account')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160)),
                ('definition', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='accounts.account')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['account', 'status'], name='contacts_co_account_89593a_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['account', 'last_engaged_at'], name='contacts_co_account_f67d8b_idx'),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('account', 'email'), name='uniq_contact_account_email'),
        ),
        migrations.AddIndex(
            model_name='contactevent',
            index=models.Index(fields=['contact', 'occurred_at'], name='contacts_co_contact_ad5ad4_idx'),
        ),
        migrations.AddIndex(
            model_name='contactevent',
            index=models.Index(fields=['account', 'type', 'occurred_at'], name='contacts_co_account_4517e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactlistmembership',
            constraint=models.UniqueConstraint(fields=('contact', 'contact_list'), name='uniq_contactlist_membership'),
        ),
        migrations.AddConstraint(
            model_name='contactlist',
            constraint=models.UniqueConstraint(fields=('account', 'slug'), name='uniq_contactlist_account_slug'),
        ),
        migrations.AddConstraint(
            model_name='customattributedef',
            constraint=models.UniqueConstraint(fields=('account', 'key'), name='uniq_custom_attr_account_key'),
        ),
        migrations.AddConstraint(
            model_name='segment',
            constraint=models.UniqueConstraint(fields=('account', 'slug'), name='uniq_segment_account_slug'),
        ),
    ]
