# Generated by Django 6.0.6 on 2026-09-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_security_reviewed_at'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['account', 'phone'], name='contacts_co_account_dde65c_idx'),
        ),
    ]
