# Generated by Django 6.0.6 on 2026-09-24 09:03

from django.db import migrations, models


def backfill_consent(apps, schema_editor):
    """Seed consent from what we can actually prove, and nothing more.

    Existing rows predate consent tracking, so their opt-in is UNKNOWN — we
    deliberately do not backfill OPTED_IN. Claiming consent we cannot evidence
    is worse than admitting we have none, both for the recipient and for an
    SES review. Already-unsubscribed rows are unambiguous, so those carry over.
    """
    Contact = apps.get_model("contacts", "Contact")
    Contact.objects.filter(status="unsubscribed").update(
        consent_status="opted_out",
        opt_out_reason="pre_consent_backfill",
    )
    Contact.objects.exclude(status="unsubscribed").update(
        consent_status="unknown",
        consent_source="pre_consent_backfill",
    )


def unbackfill_consent(apps, schema_editor):
    """No-op: the fields themselves are removed on the way back down."""


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_security_reviewed_at'),
        ('contacts', '0003_contact_optional_email_and_phone_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='consent_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='contact',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='consent_source',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='consent_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('opted_in', 'Opted in'), ('opted_out', 'Opted out')], default='unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='opt_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='opt_out_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['account', 'consent_status'], name='contacts_co_account_2ac9c5_idx'),
        ),
        migrations.RunPython(backfill_consent, unbackfill_consent),
    ]
