# Generated by Django 6.1.1 on 2026-10-01 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0006_import_limit_skipped"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="lifecycle_stage",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("imported", "Imported"),
                    ("validated", "Validated"),
                    ("engaged", "Engaged"),
                    ("customer", "Customer"),
                    ("repeat_customer", "Repeat Customer"),
                    ("inactive", "Inactive"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="quality_score",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="quality_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ContactEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("is_valid_format", models.BooleanField(default=False)),
                ("domain_valid", models.BooleanField(default=False)),
                (
                    "deliverability_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("bounced", "Bounced"),
                        ],
                        default="unknown",
                        max_length=10,
                    ),
                ),
                ("last_checked", models.DateTimeField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_emails",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["contact", "is_primary"],
                        name="contacts_co_contact_bafbc2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ContactPhone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_value", models.CharField(max_length=30)),
                (
                    "normalized_value",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("country", models.CharField(blank=True, default="", max_length=2)),
                ("is_valid_format", models.BooleanField(default=False)),
                (
                    "whatsapp_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Unknown"),
                            ("confirmed", "Confirmed"),
                            ("unreachable", "Unreachable"),
                        ],
                        default="unknown",
                        max_length=12,
                    ),
                ),
                ("whatsapp_checked_at", models.DateTimeField(blank=True, null=True)),
                ("is_primary", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_phones",
                        to="contacts.contact",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_primary", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["contact", "is_primary"],
                        name="contacts_co_contact_dcc82d_idx",
                    ),
                    models.Index(
                        fields=["contact", "whatsapp_status"],
                        name="cx_phone_wa_status_idx",
                    ),
                ],
            },
        ),
    ]
