# Generated by Django 6.0.6 on 2026-08-27 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="automationrule",
            name="whatsapp_au_account_7f7c6d_idx",
        ),
        migrations.DeleteModel(
            name="AutomationRule",
        ),
    ]
