# Generated by Django 6.0.6 on 2026-06-13 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_alter_bitrixaccount_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppBusinessNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('waba_id', models.CharField(blank=True, max_length=50, null=True)),
                ('display_number', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bitrix_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_numbers', to='whatsapp.bitrixaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number_id'], name='whatsapp_wh_phone_n_7071dc_idx'), models.Index(fields=['is_active', 'phone_number_id'], name='whatsapp_wh_is_acti_fa8e43_idx')],
                'unique_together': {('bitrix_account', 'phone_number_id')},
            },
        ),
    ]
