# Generated by Django 6.0.6 on 2026-09-04 07:40

from django.db import migrations

import apps.accounts.fields


class Migration(migrations.Migration):
    dependencies = [
        ("whatsapp", "0008_outboundmessage_error_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappbusinessnumber",
            name="verification_pin",
            field=apps.accounts.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
