# Generated by Django 6.0.6 on 2026-09-19 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0011_registration_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=10)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_code', models.CharField(blank=True, default='', max_length=32)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_tests', to='whatsapp.whatsappbusinessnumber')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['number', 'status', '-created_at'], name='whatsapp_co_number__dacd4a_idx')],
            },
        ),
    ]
