# Generated by Django 6.0.6 on 2026-09-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0013_whatsappcampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='buttons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='footer',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='header',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='variable_examples',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
