# Generated by Django 6.1.1 on 2026-09-29 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0006_import_limit_skipped"),
        ("whatsapp", "0016_held_unconfirmed"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappcampaign",
            name="variable_fallbacks",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="WhatsAppCampaignRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("queued", "Queued"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                            ("held", "Held"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "skip_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("opted_out", "Opted out"),
                            ("no_whatsapp_identity", "No WhatsApp number"),
                            ("missing_value", "Missing template value"),
                        ],
                        default="",
                        max_length=25,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="whatsapp.whatsappcampaign",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contacts.contact",
                    ),
                ),
                (
                    "message",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_recipient",
                        to="whatsapp.outboundmessage",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["campaign", "status"],
                        name="whatsapp_wh_campaig_be2a41_idx",
                    ),
                    models.Index(
                        fields=["campaign", "skip_reason"],
                        name="whatsapp_wh_campaig_80a298_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "contact"),
                        name="unique_whatsapp_campaign_contact",
                    )
                ],
            },
        ),
    ]
