# Generated by Django 6.1.1 on 2026-09-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whatsapp", "0017_campaign_recipient"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappcampaign",
            name="last_progress_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
