# Generated by Django 6.1.1 on 2026-10-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("whatsapp", "0019_registration_attempts_lockout"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappbusinessnumber",
            name="token_expired",
            field=models.BooleanField(default=False),
        ),
    ]
