# Generated by Django 6.0.6 on 2026-08-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_add_mail_provider_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="automation_events_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable domain event publishing for automation rules and AI (Phase 1 beta)",
            ),
        ),
    ]
