# Generated by Django 6.0.6 on 2026-08-28 07:35

from django.db import migrations, models

import apps.accounts.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_configurations"),
    ]

    operations = [
        migrations.AddField(
            model_name="configurations",
            name="is_secret",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="configurations",
            name="value",
            field=apps.accounts.fields.EncryptedTextField(),
        ),
    ]
