# Generated by Django 6.0.6 on 2026-08-30 09:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_configurations_is_secret"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitesettings",
            name="bitrix_enabled",
        ),
    ]
