# Generated by Django 6.1.1 on 2026-10-03 05:25

import django.db.models.deletion
from django.db import migrations, models

import apps.chatbot.models.config
import apps.chatbot.models.session


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0011_pilotenrollment"),
        ("ai", "0006_knowledgebaseentry"),
        ("contacts", "0007_contact_intelligence"),
        (
            "conversations",
            "0013_conversationform_flow_error_conversationform_flow_id_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80)),
                ("label", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Shown to the LLM as the tool description.",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Chatbot action",
                "verbose_name_plural": "Chatbot actions",
            },
        ),
        migrations.CreateModel(
            name="ChatbotConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_key",
                    models.CharField(
                        default=apps.chatbot.models.config._default_public_key,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("support", "Support"),
                            ("sales", "Sales"),
                            ("general", "General assistant"),
                            ("custom", "Custom"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("avatar_url", models.URLField(blank=True)),
                ("welcome_message", models.TextField(blank=True)),
                ("primary_color", models.CharField(default="#1a56db", max_length=7)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("bottom_right", "Bottom right"),
                            ("bottom_left", "Bottom left"),
                        ],
                        default="bottom_right",
                        max_length=20,
                    ),
                ),
                ("allowed_domains", models.JSONField(default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbots",
                        to="accounts.account",
                    ),
                ),
                (
                    "handoff_action",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="chatbot.chatbotaction",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chatbot config",
                "verbose_name_plural": "Chatbot configs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="chatbotaction",
            name="chatbot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="actions",
                to="chatbot.chatbotconfig",
            ),
        ),
        migrations.CreateModel(
            name="ChatbotKnowledgeSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "chatbot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_sources",
                        to="chatbot.chatbotconfig",
                    ),
                ),
                (
                    "knowledge_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chatbot_sources",
                        to="ai.knowledgebaseentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chatbot knowledge source",
                "verbose_name_plural": "Chatbot knowledge sources",
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        default=apps.chatbot.models.session._default_session_key,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("visitor_name", models.CharField(blank=True, max_length=200)),
                ("visitor_email", models.EmailField(blank=True, max_length=254)),
                ("identified_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity_at", models.DateTimeField(auto_now=True)),
                (
                    "chatbot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="chatbot.chatbotconfig",
                    ),
                ),
                (
                    "contact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_sessions",
                        to="contacts.contact",
                    ),
                ),
                (
                    "conversation",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_session",
                        to="conversations.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat session",
                "verbose_name_plural": "Chat sessions",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatActionExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("authorized", "Authorized"),
                            ("denied", "Denied"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("input_metadata", models.JSONField(default=dict)),
                ("output_metadata", models.JSONField(default=dict)),
                ("error", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "action",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="chatbot.chatbotaction",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="action_executions",
                        to="chatbot.chatsession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat action execution",
                "verbose_name_plural": "Chat action executions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="chatbotaction",
            constraint=models.UniqueConstraint(
                fields=("chatbot", "slug"), name="unique_chatbot_action"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatbotknowledgesource",
            constraint=models.UniqueConstraint(
                fields=("chatbot", "knowledge_entry"),
                name="unique_chatbot_knowledge_source",
            ),
        ),
    ]
