# Generated by Django 6.1.1 on 2026-10-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="visitor_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
