# Generated by Django 6.1.1 on 2026-10-03 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_add_visitor_phone"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower = appears first."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Chatbot category",
                "verbose_name_plural": "Chatbot categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.AddField(
            model_name="chatbotconfig",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="chatbots",
                to="chatbot.chatbotcategory",
            ),
        ),
    ]
