# Generated by Django 6.0.6 on 2026-08-27 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0003_invitation"),
        (
            "whatsapp",
            "0002_remove_automationrule_whatsapp_au_account_7f7c6d_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomationRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "trigger_event",
                    models.CharField(
                        choices=[
                            ("message_received", "Message received"),
                            ("message_sent", "Message sent"),
                            ("lead_created", "Lead created"),
                            ("deal_stage_changed", "Deal stage changed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("conditions", models.JSONField(default=dict)),
                ("action", models.JSONField(default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "db_table": "whatsapp_automationrule",
                "indexes": [
                    models.Index(
                        fields=["account", "trigger_event", "is_active"],
                        name="whatsapp_au_account_7f7c6d_idx",
                    )
                ],
            },
        ),
    ]
