# Generated by Django 6.0.6 on 2026-09-10 13:25

from django.db import migrations, models


def dedupe_step_runs(apps, schema_editor):
    """Drop duplicate (run, step_id) WorkflowStepRun rows, keeping the earliest.

    A double-executing advance_run could historically write two rows for one
    step; the unique constraint added below would fail against them. Pre-launch
    there should be none, but this keeps the migration safe on any dataset.
    """
    WorkflowStepRun = apps.get_model("automation", "WorkflowStepRun")
    seen: set = set()
    dup_ids: list = []
    for pk, run_id, step_id in (
        WorkflowStepRun.objects.order_by("pk").values_list("pk", "run_id", "step_id")
    ):
        key = (run_id, step_id)
        if key in seen:
            dup_ids.append(pk)
        else:
            seen.add(key)
    if dup_ids:
        WorkflowStepRun.objects.filter(pk__in=dup_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_workflow_workflowrun_workflowsteprun_and_more'),
    ]

    operations = [
        migrations.RunPython(dedupe_step_runs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='workflowsteprun',
            constraint=models.UniqueConstraint(fields=('run', 'step_id'), name='uniq_workflowsteprun_run_step'),
        ),
    ]
