# Generated by Django 6.0.6 on 2026-09-17 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_workflowsteprun_uniq_workflowsteprun_run_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowWebhookDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=64)),
                ('url', models.URLField(max_length=1000)),
                ('method', models.CharField(default='POST', max_length=10)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('body', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('exhausted', 'Exhausted')], default='pending', max_length=20)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('response_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='automation.workflowrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['run', 'step_id'], name='automation__run_id_82cbee_idx')],
            },
        ),
    ]
