# Generated by Django 6.1.1 on 2026-10-10 06:15

import apps.automation.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_dismissedsuggestion_replypattern'),
        ('conversations', '0019_phase6_rec_log_action_conversation'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.automation.models._workflow_interaction_token, editable=False, max_length=22, unique=True)),
                ('step_id', models.CharField(max_length=64)),
                ('expected', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='open', max_length=12)),
                ('invalid_answer_count', models.PositiveSmallIntegerField(default=0)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_interactions', to='conversations.conversation')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='automation.workflowrun')),
            ],
        ),
        migrations.CreateModel(
            name='InteractionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='automation.workflowinteraction')),
            ],
        ),
        migrations.AddIndex(
            model_name='workflowinteraction',
            index=models.Index(fields=['conversation', 'status'], name='automation__convers_ec9ba4_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowinteraction',
            index=models.Index(fields=['run', 'step_id'], name='automation__run_id_99e438_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowinteraction',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('run', 'step_id'), name='uniq_open_interaction_run_step'),
        ),
        migrations.AddIndex(
            model_name='interactionanswer',
            index=models.Index(fields=['interaction'], name='automation__interac_fe6de8_idx'),
        ),
    ]
