# Generated by Django 6.1.1 on 2026-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SEOPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="URL path, e.g. /features/whatsapp/",
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=70)),
                ("description", models.CharField(blank=True, max_length=160)),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Override only for intentional canonicalization (duplicate/alternate URLs). Leave blank to auto-generate from the request path.",
                    ),
                ),
                ("og_image", models.ImageField(blank=True, upload_to="seo/")),
                ("noindex", models.BooleanField(default=False)),
                (
                    "sitemap",
                    models.BooleanField(
                        default=True,
                        help_text="Include this URL in the XML sitemap. Automatically set to False when noindex is True.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "SEO page",
                "verbose_name_plural": "SEO pages",
                "ordering": ["path"],
            },
        ),
    ]
