# Generated by Django 6.1.1 on 2026-10-01 13:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0010_business_context"),
        ("contacts", "0007_contact_intelligence"),
        (
            "conversations",
            "0013_conversationform_flow_error_conversationform_flow_id_and_more",
        ),
        ("crm", "0002_conversation_attribution"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="lead",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["new", "contacted", "qualified"])),
                fields=("account", "contact"),
                name="unique_open_lead_per_contact",
            ),
        ),
    ]
