# Generated by Django 6.1.1 on 2026-10-04 16:00

import apps.accounts.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_seed_platform_account'),
        ('contacts', '0007_contact_intelligence'),
        ('conversations', '0014_add_website_chat_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramBusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_business_account_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('page_id', models.CharField(blank=True, default='', max_length=50)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('access_token', apps.accounts.fields.EncryptedTextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('token_expired', models.BooleanField(default=False)),
                ('verify_token', models.CharField(max_length=64)),
                ('webhook_subscribed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_accounts', to='accounts.account')),
            ],
            options={
                'unique_together': {('account', 'instagram_business_account_id')},
            },
        ),
        migrations.CreateModel(
            name='InstagramContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_scoped_id', models.CharField(db_index=True, max_length=50)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('opted_out', models.BooleanField(default=False)),
                ('messaging_eligible', models.BooleanField(default=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_contacts', to='accounts.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_contacts', to='contacts.contact')),
            ],
        ),
        migrations.CreateModel(
            name='CommentThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(db_index=True, max_length=50)),
                ('post_type', models.CharField(choices=[('post', 'Post'), ('reel', 'Reel'), ('story', 'Story'), ('live', 'Live'), ('ad', 'Ad')], default='post', max_length=10)),
                ('comment_id', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('intent', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField()),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instagram_comment_threads', to='conversations.conversation')),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_threads', to='instagram.instagrambusinessaccount')),
                ('instagram_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_threads', to='instagram.instagramcontact')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=50)),
                ('parent_comment_id', models.CharField(blank=True, default='', max_length=50)),
                ('body', models.TextField()),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], default='inbound', max_length=10)),
                ('is_hidden', models.BooleanField(default=False)),
                ('moderation_state', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('hidden', 'Hidden'), ('deleted', 'Deleted')], default='pending', max_length=10)),
                ('timestamp', models.DateTimeField()),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instagram.commentthread')),
                ('instagram_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='instagram.instagramcontact')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='instagram.instagrambusinessaccount')),
                ('instagram_contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='instagram.instagramcontact')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=100)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='', max_length=20)),
                ('timestamp', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('comment_thread', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='instagram.commentthread')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='instagram.instagramconversation')),
            ],
        ),
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('recipient_igsid', models.CharField(max_length=50)),
                ('action_type', models.CharField(choices=[('dm_reply', 'DM Reply'), ('comment_reply', 'Comment Reply'), ('private_reply', 'Private Reply to Comment')], max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('unconfirmed', 'May not have been sent')], default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=100)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_messages', to='instagram.instagrambusinessaccount')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=255)),
                ('event_type', models.CharField(choices=[('message', 'DM Message'), ('comment', 'Comment'), ('mention', 'Mention'), ('status', 'Status Update'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=20)),
                ('raw_payload', models.JSONField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('instagram_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='instagram.instagrambusinessaccount')),
            ],
        ),
        migrations.AddConstraint(
            model_name='instagramcontact',
            constraint=models.UniqueConstraint(fields=('account', 'instagram_scoped_id'), name='unique_instagram_contact_per_account'),
        ),
        migrations.AddIndex(
            model_name='commentthread',
            index=models.Index(fields=['instagram_account', 'post_id'], name='instagram_c_instagr_4a8745_idx'),
        ),
        migrations.AddIndex(
            model_name='commentthread',
            index=models.Index(fields=['intent', 'received_at'], name='instagram_c_intent_da8b0e_idx'),
        ),
        migrations.AddConstraint(
            model_name='commentthread',
            constraint=models.UniqueConstraint(fields=('instagram_account', 'comment_id'), name='unique_comment_thread_per_account'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('thread', 'comment_id'), name='unique_comment_per_thread'),
        ),
        migrations.AddIndex(
            model_name='instagramconversation',
            index=models.Index(fields=['instagram_contact', 'is_open'], name='instagram_i_instagr_8e08d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='instagramconversation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_open', True)), fields=('instagram_account', 'instagram_contact'), name='one_open_instagram_conversation_per_contact'),
        ),
        migrations.AddIndex(
            model_name='instagrammessage',
            index=models.Index(fields=['conversation', 'timestamp'], name='instagram_i_convers_d0e264_idx'),
        ),
        migrations.AddConstraint(
            model_name='instagrammessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment_thread__isnull', True), ('conversation__isnull', False)), models.Q(('comment_thread__isnull', False), ('conversation__isnull', True)), _connector='OR'), name='instagram_message_exactly_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='instagrammessage',
            constraint=models.UniqueConstraint(fields=('message_id',), name='unique_instagram_message_id'),
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['status', 'created_at'], name='instagram_o_status_e77730_idx'),
        ),
        migrations.AddIndex(
            model_name='outboundmessage',
            index=models.Index(fields=['instagram_account', 'status'], name='instagram_o_instagr_8c324a_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventlog',
            index=models.Index(fields=['status', 'received_at'], name='instagram_w_status_1e9921_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookeventlog',
            index=models.Index(fields=['instagram_account', 'event_type'], name='instagram_w_instagr_2a1e5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='webhookeventlog',
            constraint=models.UniqueConstraint(condition=models.Q(('instagram_account__isnull', False)), fields=('instagram_account', 'event_id'), name='unique_instagram_webhook_event'),
        ),
    ]
