# Generated by Django 6.1.1 on 2026-10-04 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_seed_platform_account"),
        ("instagram", "0002_phase2_moderation"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentthread",
            name="trigger_fired_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="CommentTrigger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("keyword", "Keyword / phrase match"),
                            ("buying_intent", "Buying intent"),
                            ("any_comment", "Any comment"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated keywords for KEYWORD match type.",
                    ),
                ),
                (
                    "reply_template",
                    models.TextField(
                        help_text="Private reply text. Use {username} to address the commenter."
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instagram_comment_triggers",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "is_active", "priority"],
                        name="instagram_c_account_d27670_idx",
                    )
                ],
            },
        ),
    ]
