# Generated by Django 6.1.1 on 2026-10-06 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instagram", "0004_provider_message_id_widen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instagrammessage",
            name="message_id",
            field=models.CharField(max_length=500),
        ),
    ]
