# Generated by Django 6.1.1 on 2026-10-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instagram", "0006_instagramconversation_last_inbound_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moderationrule",
            name="automation_trigger",
            field=models.CharField(
                choices=[
                    ("none", "No automation"),
                    ("notify_staff", "Notify assigned staff / team"),
                    ("create_proposal", "Open a lead (potential sale)"),
                ],
                default="none",
                max_length=20,
            ),
        ),
    ]
