# Generated by Django 6.1.1 on 2026-10-08 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instagram", "0007_moderation_create_proposal_opens_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="instagrammessage",
            name="media_attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="instagrammessage",
            name="media_error",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="instagrammessage",
            name="media_file",
            field=models.FileField(
                blank=True, null=True, upload_to="instagram/media/%Y/%m/"
            ),
        ),
        migrations.AddField(
            model_name="instagrammessage",
            name="media_mime_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="instagrammessage",
            name="media_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="instagrammessage",
            name="media_source_url",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="instagrammessage",
            name="media_type",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
