# Generated by Django 6.1.1 on 2026-10-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instagram", "0008_instagrammessage_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundmessage",
            name="media_kind",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="media_mime_type",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="media_path",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
