# Generated by Django 6.1.1 on 2026-10-08 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("instagram", "0010_clear_page_id_on_instagram_login_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="moderation_state",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("flagged", "Flagged for review"),
                    ("hidden", "Hidden"),
                    ("deleted", "Deleted"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
