# Generated by Django 6.1.1 on 2026-10-02 13:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.support.models.ticket


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0011_pilotenrollment"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("general", "General Support"),
                            ("account", "Account & Access"),
                            ("onboarding", "Onboarding"),
                            ("whatsapp", "WhatsApp"),
                            ("email", "Email"),
                            ("conversations", "Conversations"),
                            ("crm", "CRM"),
                            ("payments", "Payments"),
                            ("billing", "Billing"),
                            ("integrations", "Integrations"),
                            ("technical", "Technical"),
                            ("security", "Security"),
                        ],
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("restricted", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SLAPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_tier",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Tier 1 — Standard"),
                            (2, "Tier 2 — Growth"),
                            (3, "Tier 3 — Business"),
                            (4, "Tier 4 — Enterprise / Strategic"),
                        ]
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("p1", "P1 — Critical"),
                            ("p2", "P2 — High"),
                            ("p3", "P3 — Normal"),
                            ("p4", "P4 — Low"),
                        ],
                        max_length=2,
                    ),
                ),
                ("first_response_minutes", models.PositiveIntegerField()),
                (
                    "update_frequency_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("resolution_minutes", models.PositiveIntegerField()),
                (
                    "escalation_after_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "SLA Policy",
                "verbose_name_plural": "SLA Policies",
                "ordering": ["customer_tier", "priority"],
                "unique_together": {("customer_tier", "priority")},
            },
        ),
        migrations.CreateModel(
            name="SupportCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("account", "Account"),
                            ("organization", "Organization"),
                            ("onboarding", "Onboarding"),
                            ("channels", "Channels"),
                            ("conversations", "Conversations"),
                            ("crm", "CRM"),
                            ("automation", "Automation"),
                            ("payments", "Payments"),
                            ("billing", "Billing"),
                            ("integrations", "Integrations"),
                            ("technical", "Technical"),
                            ("security", "Security"),
                            ("general", "General"),
                        ],
                        max_length=60,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="support.supportcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Support Category",
                "verbose_name_plural": "Support Categories",
                "ordering": ["sort_order", "name"],
                "unique_together": {("slug", "parent")},
            },
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_number",
                    models.CharField(
                        default=apps.support.models.ticket._ticket_number,
                        editable=False,
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "customer_tier",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Tier 1 — Standard"),
                            (2, "Tier 2 — Growth"),
                            (3, "Tier 3 — Business"),
                            (4, "Tier 4 — Enterprise / Strategic"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("p1", "P1 — Critical"),
                            ("p2", "P2 — High"),
                            ("p3", "P3 — Normal"),
                            ("p4", "P4 — Low"),
                        ],
                        default="p3",
                        max_length=2,
                    ),
                ),
                (
                    "severity_note",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("triaged", "Triaged"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("waiting_customer", "Waiting on Customer"),
                            ("waiting_internal", "Waiting Internal"),
                            ("escalated", "Escalated"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                (
                    "support_level",
                    models.CharField(
                        choices=[
                            ("l1", "L1 — Customer Support"),
                            ("l2", "L2 — Product / Technical"),
                            ("l3", "L3 — Engineering / Specialist"),
                            ("l4", "L4 — External / Infrastructure"),
                        ],
                        default="l1",
                        max_length=2,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("sla_due_at", models.DateTimeField(blank=True, null=True)),
                ("sla_breached", models.BooleanField(default=False)),
                ("first_response_at", models.DateTimeField(blank=True, null=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to="accounts.account",
                    ),
                ),
                (
                    "assigned_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="support.supportcategory",
                    ),
                ),
                (
                    "queue",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="support.supportqueue",
                    ),
                ),
                (
                    "sla_policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="support.slapolicy",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_from_customer", models.BooleanField(default=False)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportInternalNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_internal_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="internal_notes",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Ticket created"),
                            ("status_changed", "Status changed"),
                            ("priority_changed", "Priority changed"),
                            ("assigned", "Assigned to agent"),
                            ("escalated", "Escalated"),
                            ("sla_breached", "SLA breached"),
                            ("first_response", "First response sent"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                            ("reopened", "Reopened"),
                            ("note_added", "Internal note added"),
                            ("reference_added", "Reference added"),
                        ],
                        max_length=30,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportEscalation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_level", models.CharField(max_length=2)),
                ("to_level", models.CharField(max_length=2)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("manual", "Manual escalation"),
                            ("sla_breach", "SLA breach"),
                            ("tier_rule", "Customer tier rule"),
                            ("amount_rule", "Amount threshold rule"),
                            ("security", "Security incident"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "escalated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_escalations_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="escalations",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="support/attachments/%Y/%m/")),
                ("filename", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="support.supportmessage",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="support.supportticket",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupportAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_assignments_from",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_assignments_to",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="SupportTicketReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=255)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("related", "Related"),
                            ("caused_by", "Caused by"),
                            ("affects", "Affects"),
                        ],
                        default="related",
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, default="", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="references",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ticket Reference",
            },
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["account", "status"], name="support_sup_account_6086ea_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["priority", "status"], name="support_sup_priorit_19dd91_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticket",
            index=models.Index(
                fields=["sla_due_at"], name="support_sup_sla_due_a40972_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="supportticketreference",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="support_sup_content_179cf1_idx",
            ),
        ),
    ]
