# Generated by Django 6.0.6 on 2026-09-09 09:41

import apps.logs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_account_security_reviewed_at'),
        ('email_service', '0023_alter_emailmessage_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=apps.logs.models._event_public_id, editable=False, max_length=40, unique=True)),
                ('type', models.CharField(choices=[('accepted', 'Accepted'), ('queued', 'Queued'), ('rendered', 'Rendered'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('deferred', 'Deferred'), ('bounced', 'Bounced'), ('complained', 'Complained'), ('rejected', 'Rejected'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('failed', 'Failed'), ('unsubscribed', 'Unsubscribed')], max_length=20)),
                ('source', models.CharField(choices=[('pipeline', 'Send pipeline'), ('ses_sns', 'SES / SNS notification'), ('tracking_pixel', 'Open-tracking pixel'), ('tracking_link', 'Click-tracking link'), ('api', 'API'), ('sandbox', 'Sandbox provider')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('provider_event_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('request_id', models.CharField(blank=True, default='', max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_events', to='accounts.account')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='email_service.emailmessage')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
                'indexes': [models.Index(fields=['message', 'occurred_at'], name='logs_messag_message_d22756_idx'), models.Index(fields=['account', 'type', 'occurred_at'], name='logs_messag_account_78457f_idx')],
            },
        ),
    ]
