# Generated by Django 6.0.6 on 2026-09-09 09:57

import apps.logs.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_account_security_reviewed_at'),
        ('email_service', '0024_emailmessage_public_id'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.CharField(default=apps.logs.models._request_public_id, editable=False, max_length=40, unique=True)),
                ('key_mode', models.CharField(blank=True, default='', max_length=10)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('version', models.CharField(blank=True, default='', max_length=10)),
                ('status_code', models.PositiveIntegerField()),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('idempotency_key', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_replayed', models.BooleanField(default=False)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('request_headers', models.JSONField(blank=True, default=dict)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('client_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_requests', to='accounts.account')),
                ('api_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_service.emailapikey')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['account', 'created_at'], name='logs_apireq_account_434fd6_idx'), models.Index(fields=['status_code', 'created_at'], name='logs_apireq_status__4bccfe_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('endpoint', models.CharField(max_length=128)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=12)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='accounts.account')),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='logs_idempo_created_fa03ed_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'key'), name='uniq_idempotency_account_key')],
            },
        ),
        migrations.CreateModel(
            name='MessageStatsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('key_mode', models.CharField(default='live', max_length=10)),
                ('sent', models.PositiveIntegerField(default=0)),
                ('delivered', models.PositiveIntegerField(default=0)),
                ('bounced', models.PositiveIntegerField(default=0)),
                ('complained', models.PositiveIntegerField(default=0)),
                ('rejected', models.PositiveIntegerField(default=0)),
                ('opened', models.PositiveIntegerField(default=0)),
                ('clicked', models.PositiveIntegerField(default=0)),
                ('unique_opens', models.PositiveIntegerField(default=0)),
                ('unique_clicks', models.PositiveIntegerField(default=0)),
                ('unsubscribed', models.PositiveIntegerField(default=0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_stats', to='accounts.account')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_service.bulkemailcampaign')),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='email_service.emaildomain')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_service.emailtemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'day'], name='logs_messag_account_e12a42_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'domain', 'template', 'campaign', 'day', 'key_mode'), name='uniq_message_stats_dims')],
            },
        ),
    ]
