# Generated by Django 6.1.1 on 2026-10-04 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_pilotenrollment"),
        ("email_service", "0037_mail_from_dns_diagnostics"),
        ("logs", "0002_apirequest_idempotencyrecord_messagestatsdaily"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrowserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                (
                    "user_id_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 of user.pk — no PII stored.",
                        max_length=64,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField()),
                ("release", models.CharField(blank=True, default="", max_length=64)),
                ("browser", models.CharField(blank=True, default="", max_length=100)),
                (
                    "device",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="desktop | mobile | tablet",
                        max_length=40,
                    ),
                ),
                (
                    "replay_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Populated in Phase 4 when a replay SDK is configured.",
                        max_length=128,
                    ),
                ),
                (
                    "entry_path",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "ordering": ["-last_seen_at"],
            },
        ),
        migrations.CreateModel(
            name="UxEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("rage_click", "Rage click"),
                            ("dead_click", "Dead click"),
                            ("rapid_navigation", "Rapid navigation"),
                            ("repeated_form_failure", "Repeated form failure"),
                            ("js_error", "JS error"),
                        ],
                        max_length=40,
                    ),
                ),
                ("page", models.CharField(blank=True, default="", max_length=255)),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Sanitised CSS selector; no attribute values containing user data.",
                        max_length=255,
                    ),
                ),
                (
                    "click_count",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Bounded at 16 KB in the ingest view.",
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="Nearest backend request ID known to the frontend at event time.",
                        max_length=64,
                    ),
                ),
                (
                    "sentry_event_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddField(
            model_name="apirequest",
            name="browser_session_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="apirequest",
            name="op_meta",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Server-generated structured diagnostic context only. Never copy request.POST or request.data here.",
            ),
        ),
        migrations.AddField(
            model_name="apirequest",
            name="release",
            field=models.CharField(
                blank=True,
                default="",
                help_text="RELEASE_VERSION at request time.",
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="apirequest",
            index=models.Index(
                fields=["browser_session_id", "-created_at"],
                name="logs_apireq_browser_b2e60f_idx",
            ),
        ),
        migrations.AddField(
            model_name="browsersession",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="browser_sessions",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="uxevent",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ux_events",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="uxevent",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ux_events",
                to="logs.browsersession",
            ),
        ),
        migrations.AddIndex(
            model_name="browsersession",
            index=models.Index(
                fields=["account", "-last_seen_at"],
                name="logs_browse_account_c734de_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="browsersession",
            index=models.Index(
                fields=["-last_seen_at"], name="logs_browse_last_se_1ce508_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="uxevent",
            index=models.Index(
                fields=["session", "-occurred_at"],
                name="logs_uxeven_session_112a1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uxevent",
            index=models.Index(
                fields=["account", "-occurred_at"],
                name="logs_uxeven_account_e417df_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="uxevent",
            index=models.Index(
                fields=["type", "-occurred_at"], name="logs_uxeven_type_b9fe96_idx"
            ),
        ),
    ]
