# Generated by Django 6.0.6 on 2026-09-25 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_business_hours'),
        ('ai', '0001_initial'),
        ('conversations', '0004_conversation_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproposal',
            name='extras',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aiproposal',
            name='tools_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='AIConversationMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='')),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('covered_until_id', models.BigIntegerField(default=0)),
                ('model', models.CharField(blank=True, default='', max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.account')),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_memory', to='conversations.conversation')),
            ],
        ),
    ]
