# Generated by Django 6.0.6 on 2026-09-25 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_memory_extras_tools'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aiproposal',
            name='auto_decision',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='aiproposal',
            name='auto_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aiproposal',
            name='intent',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='aiproposal',
            name='route',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='auto_consented_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='auto_consented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='auto_min_confidence',
            field=models.FloatField(default=0.85),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='auto_only_when_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='auto_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='aisettings',
            name='reply_mode',
            field=models.CharField(choices=[('suggest', 'Suggest replies for my team to send'), ('auto', 'Reply automatically to the questions I choose')], default='suggest', max_length=10),
        ),
    ]
