# Generated by Django 6.1.1 on 2026-09-30 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_team"),
        ("ai", "0005_email_drafts"),
    ]

    operations = [
        migrations.CreateModel(
            name="KnowledgeBaseEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("faq", "FAQ"),
                            ("policy", "Policy"),
                            ("other", "Other"),
                        ],
                        default="faq",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="knowledge_base_entries",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
    ]
