# Generated by Django 6.1.1 on 2026-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0007_expire_instagram_purchase_intent"),
    ]

    operations = [
        migrations.AddField(
            model_name="aisettings",
            name="holding_reply_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="holding_reply_text",
            field=models.CharField(blank=True, default="", max_length=300),
        ),
    ]
