# Generated by Django 6.1.1 on 2026-10-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0008_holding_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgebaseentry",
            name="origin",
            field=models.CharField(
                choices=[
                    ("manual", "Written by hand"),
                    ("inbox", "From a conversation"),
                    ("import", "Imported"),
                    ("website", "From your website"),
                    ("ai_draft", "Drafted by AI"),
                ],
                default="manual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="knowledgebaseentry",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="knowledgebaseentry",
            name="source_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="aidraft",
            name="kind",
            field=models.CharField(
                choices=[
                    ("automation", "Automation"),
                    ("template", "Template"),
                    ("template_edit", "Template edit"),
                    ("email_template", "Email template"),
                    ("email_edit", "Email edit"),
                    ("playground", "Try a question"),
                    ("knowledge_answers", "Draft knowledge answers"),
                    ("website", "Read a website"),
                ],
                max_length=20,
            ),
        ),
    ]
