# Generated by Django 6.1.1 on 2026-10-01 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0009_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Insight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("opportunity", "Opportunity"),
                            ("urgent", "Urgent"),
                        ],
                        default="info",
                        max_length=12,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("body", models.TextField(blank=True, default="")),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("evidence_count", models.PositiveIntegerField(default=0)),
                ("suggested_action", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("acknowledged", "Acknowledged"),
                            ("acted_on", "Acted on"),
                            ("dismissed", "Dismissed"),
                            ("resolved", "Resolved"),
                        ],
                        default="new",
                        max_length=14,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecommendationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recommended_at", models.DateTimeField(auto_now_add=True)),
                ("accepted", models.BooleanField(blank=True, null=True)),
                ("acted_at", models.DateTimeField(blank=True, null=True)),
                ("outcome_measured_at", models.DateTimeField(blank=True, null=True)),
                ("outcome_summary", models.JSONField(blank=True, default=dict)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to="accounts.account",
                    ),
                ),
                (
                    "insight",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_logs",
                        to="insights.insight",
                    ),
                ),
            ],
            options={
                "ordering": ["-recommended_at"],
            },
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                fields=["account", "status"], name="insights_in_account_f42098_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                fields=["account", "type", "status"],
                name="insights_in_account_fb5aa1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="insight",
            index=models.Index(
                fields=["account", "severity", "status"],
                name="insights_in_account_7bcf34_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="insight",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", ["new", "acknowledged"])),
                fields=("account", "type"),
                name="uniq_open_insight_per_type",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationlog",
            index=models.Index(
                fields=["account", "recommended_at"],
                name="insights_re_account_9ebde9_idx",
            ),
        ),
    ]
