# Generated by Django 6.1.1 on 2026-10-02 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_pilotenrollment"),
        ("insights", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "trigger",
                    models.CharField(
                        choices=[
                            ("conversation_unanswered", "Conversation unanswered"),
                            ("lead_unanswered", "Lead unanswered"),
                            ("customer_inactive", "Customer inactive"),
                            ("repurchase_due", "Repurchase window elapsed"),
                        ],
                        max_length=64,
                    ),
                ),
                ("condition", models.JSONField(blank=True, default=dict)),
                ("action", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="accounts.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="derived_policies",
                        to="insights.insight",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "business policies",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["account", "status"],
                        name="insights_bu_account_0b05f2_idx",
                    ),
                    models.Index(
                        fields=["account", "trigger", "status"],
                        name="insights_bu_account_446feb_idx",
                    ),
                ],
            },
        ),
    ]
