# Generated by Django 6.1.1 on 2026-10-02 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_pilotenrollment"),
        ("insights", "0002_businesspolicy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="businesspolicy",
            constraint=models.UniqueConstraint(
                condition=models.Q(("created_from__isnull", False)),
                fields=("account", "created_from"),
                name="uniq_policy_per_insight",
            ),
        ),
    ]
