# Generated by Django 6.1.1 on 2026-10-02 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_pilotenrollment"),
        ("insights", "0003_businesspolicy_uniq_per_insight"),
    ]

    operations = [
        migrations.AddField(
            model_name="recommendationlog",
            name="status",
            field=models.CharField(
                choices=[
                    ("presented", "Presented"),
                    ("accepted", "Accepted"),
                    ("dismissed", "Dismissed"),
                    ("expired", "Expired"),
                ],
                default="presented",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="PolicyExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trigger_snapshot", models.JSONField(blank=True, default=dict)),
                ("target", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=12,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_executions",
                        to="accounts.account",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="insights.businesspolicy",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddField(
            model_name="recommendationlog",
            name="policy_execution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="recommendation_logs",
                to="insights.policyexecution",
            ),
        ),
        migrations.AddIndex(
            model_name="recommendationlog",
            index=models.Index(
                fields=["account", "status"], name="insights_re_account_fec631_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyexecution",
            index=models.Index(
                fields=["account", "status"], name="insights_po_account_9b5585_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="policyexecution",
            index=models.Index(
                fields=["policy", "started_at"], name="insights_po_policy__8a884a_idx"
            ),
        ),
    ]
