from django.urls import path

from apps.email import views

urlpatterns = [
    path("domains/", views.domains_list, name="email-domains"),
    path("domains/create/", views.domain_create, name="email-domain-create"),
    path("domains/<int:pk>/verify/", views.domain_verify, name="email-domain-verify"),
    path("domains/<int:pk>/toggle/", views.domain_toggle, name="email-domain-toggle"),
    path("domains/<int:pk>/delete/", views.domain_delete, name="email-domain-delete"),
    path("keys/create/", views.key_create, name="email-key-create"),
    path("domains/<int:pk>/smtp/create/", views.smtp_create, name="email-smtp-create"),
    path("smtp/<int:pk>/rotate/", views.smtp_rotate, name="email-smtp-rotate"),
    path("smtp/<int:pk>/revoke/", views.smtp_revoke, name="email-smtp-revoke"),
    path("webhooks/", views.webhooks_list, name="email-webhooks"),
    path("webhooks/create/", views.webhook_create, name="email-webhook-create"),
    path("webhooks/<int:pk>/delete/", views.webhook_delete, name="email-webhook-delete"),
    path("webhooks/deliveries/<int:pk>/resend/", views.webhook_redeliver, name="email-webhook-redeliver"),
    path("insights/", views.insights, name="email-insights"),
    path("mailboxes/", views.mailbox_list, name="email-mailboxes"),
    path("mailboxes/create/", views.mailbox_create, name="email-mailbox-create"),
    path("mailboxes/<int:pk>/delete/", views.mailbox_delete, name="email-mailbox-delete"),
    path("mailboxes/<int:pk>/password/", views.mailbox_password, name="email-mailbox-password"),
    path("mailboxes/<int:pk>/quota/", views.mailbox_quota, name="email-mailbox-quota"),
    path("aliases/create/", views.alias_create, name="email-alias-create"),
    path("send/", views.api_send, name="email-send"),
    path("t/open/<str:token>/", views.tracking_open, name="email-tracking-open"),
    path("t/click/<str:token>/", views.tracking_click, name="email-tracking-click"),
    path("templates/", views.templates_list, name="email-templates"),
    path("templates/create/", views.template_create, name="email-template-create"),
    path("templates/<int:pk>/", views.template_edit_form, name="email-template-detail"),
    path("templates/<int:pk>/edit/", views.template_edit, name="email-template-edit"),
    path(
        "templates/<int:pk>/versions/<int:version_pk>/restore/",
        views.template_version_restore,
        name="email-template-version-restore",
    ),
    path("templates/<int:pk>/clone/", views.template_clone, name="email-template-clone"),
    path("templates/<int:pk>/delete/", views.template_delete, name="email-template-delete"),
    path("templates/<int:pk>/preview/", views.template_preview, name="email-template-preview"),
    path("templates/<int:pk>/send-test/", views.template_send_test, name="email-template-send-test"),
    path("templates/assets/upload/", views.template_asset_upload, name="email-template-asset-upload"),
    path("templates/assets/", views.asset_library, name="email-assets"),
    path("templates/assets/<int:pk>/delete/", views.asset_delete, name="email-asset-delete"),
    path("campaigns/", views.campaigns_list, name="email-campaigns"),
    path("campaigns/create/", views.campaign_create, name="email-campaign-create"),
    path("campaigns/<int:pk>/", views.campaign_detail, name="email-campaign-detail"),
]
