# Generated by Django 6.0.6 on 2026-09-25 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_business_hours'),
        ('automation', '0006_workflowrun_subject_key'),
        ('commerce', '0002_conversation_attribution'),
        ('conversations', '0003_alter_message_direction'),
        ('crm', '0002_conversation_attribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS')], max_length=20)),
                ('method', models.CharField(choices=[('explicit', 'Explicit'), ('recent_conversation', 'Recent conversation')], max_length=24)),
                ('attributed_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='accounts.account')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='conversations.conversation')),
                ('deal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to='crm.deal')),
                ('lead', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to='crm.lead')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribution', to='commerce.order')),
                ('workflow_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attributions', to='automation.workflowrun')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'channel', 'attributed_at'], name='conversatio_account_a302fd_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('deal__isnull', True), ('lead__isnull', False), ('order__isnull', True)), models.Q(('deal__isnull', False), ('lead__isnull', True), ('order__isnull', True)), models.Q(('deal__isnull', True), ('lead__isnull', True), ('order__isnull', False)), _connector='OR'), name='attribution_exactly_one_subject')],
            },
        ),
    ]
