# Generated by Django 6.0.6 on 2026-09-28 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_operator_console"),
        ("conversations", "0006_followup_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="InsightSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("minutes_per_reply", models.PositiveSmallIntegerField(default=2)),
                ("weekly_report", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_settings",
                        to="accounts.account",
                    ),
                ),
            ],
        ),
    ]
