# Generated by Django 6.1.1 on 2026-09-29 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_operator_console"),
        ("conversations", "0007_insightsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_start", models.DateTimeField()),
                ("metrics", models.JSONField(default=dict)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_snapshots",
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "ordering": ["week_start"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "week_start"),
                        name="uniq_weeklysnapshot_account_week",
                    )
                ],
            },
        ),
    ]
