# Generated by Django 6.1.1 on 2026-09-29 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_operator_console"),
        ("conversations", "0008_weeklysnapshot"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InsightGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("median_first_reply", "Median first reply"),
                            ("answered_pct", "Conversations answered within 24 hours"),
                            ("leads", "Leads this month"),
                            ("paid_orders", "Paid orders this month"),
                            ("revenue", "Revenue this month"),
                        ],
                        max_length=24,
                    ),
                ),
                ("target", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insight_goals",
                        to="accounts.account",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["metric", "currency"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "metric", "currency"),
                        name="uniq_insightgoal_account_metric_currency",
                    )
                ],
            },
        ),
    ]
