# Generated by Django 6.1.1 on 2026-09-30 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_team"),
        ("contacts", "0006_import_limit_skipped"),
        ("conversations", "0009_insightgoal"),
        ("whatsapp", "0018_whatsappcampaign_last_progress_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RoutingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("conditions", models.JSONField(blank=True, default=dict)),
                ("priority", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
        migrations.AddField(
            model_name="conversation",
            name="assigned_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conversations",
                to="accounts.team",
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["account", "assigned_team"],
                name="conversatio_account_55780b_idx",
            ),
        ),
        migrations.AddField(
            model_name="routingrule",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routing_rules",
                to="accounts.account",
            ),
        ),
        migrations.AddField(
            model_name="routingrule",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="routing_rules",
                to="accounts.team",
            ),
        ),
    ]
