# Generated by Django 6.1.1 on 2026-09-30 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0010_routingrule_conversation_assigned_team_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="closed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resolved", "Resolved"),
                    ("no_response", "No response"),
                    ("spam", "Spam"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
