# Generated by Django 6.1.1 on 2026-09-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("conversations", "0012_conversationform_formresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationform",
            name="flow_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="conversationform",
            name="flow_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="conversationform",
            name="flow_json_hash",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="conversationform",
            name="flow_published_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversationform",
            name="flow_status",
            field=models.CharField(
                choices=[
                    ("not_created", "Not created on Meta"),
                    ("draft", "Draft (not published)"),
                    ("published", "Published"),
                    ("needs_republish", "Questions changed since publish"),
                    ("error", "Meta rejected the last publish attempt"),
                ],
                default="not_created",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="conversationform",
            name="presentation",
            field=models.CharField(
                choices=[
                    ("text", "Plain text (one question at a time)"),
                    ("whatsapp_flow", "WhatsApp Flow"),
                ],
                default="text",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="formresponse",
            name="flow_token",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
