# Generated by Django 6.1.1 on 2026-10-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "conversations",
            "0013_conversationform_flow_error_conversationform_flow_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="conversation",
            name="channel",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("website_chat", "Website Chat"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="conversationattribution",
            name="channel",
            field=models.CharField(
                choices=[
                    ("whatsapp", "WhatsApp"),
                    ("email", "Email"),
                    ("sms", "SMS"),
                    ("website_chat", "Website Chat"),
                ],
                max_length=20,
            ),
        ),
    ]
