# Generated by Django 6.1.1 on 2026-10-04 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_seed_platform_account'),
        ('contacts', '0007_contact_intelligence'),
        ('conversations', '0014_add_website_chat_channel'),
        ('instagram', '0001_initial'),
        ('whatsapp', '0020_token_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='instagram_conversation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generic_conversation', to='instagram.instagramconversation'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('website_chat', 'Website Chat'), ('instagram', 'Instagram')], max_length=20),
        ),
        migrations.AlterField(
            model_name='conversationattribution',
            name='channel',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'Email'), ('sms', 'SMS'), ('website_chat', 'Website Chat'), ('instagram', 'Instagram')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(condition=models.Q(('instagram_conversation__isnull', False)), fields=('instagram_conversation',), name='unique_generic_conversation_per_instagram_conversation'),
        ),
    ]
